// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3iAVaS_wHz7jIO5IQFg_cLfgBuMOFjy8',
    appId: '1:672524255992:web:7f00f52c45027235d2b10d',
    messagingSenderId: '672524255992',
    projectId: 'weather-app-50e4d',
    authDomain: 'weather-app-50e4d.firebaseapp.com',
    storageBucket: 'weather-app-50e4d.firebasestorage.app',
    measurementId: 'G-CDZDMBZ87M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvvZagzmaujLj_hDanAEylLMgshzxLSiM',
    appId: '1:672524255992:android:ad233e7f429a62a5d2b10d',
    messagingSenderId: '672524255992',
    projectId: 'weather-app-50e4d',
    storageBucket: 'weather-app-50e4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTojAYvyfH9gMEikMVkwljx0xQZGmO94',
    appId: '1:672524255992:ios:bdeb91260e979d6bd2b10d',
    messagingSenderId: '672524255992',
    projectId: 'weather-app-50e4d',
    storageBucket: 'weather-app-50e4d.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxTojAYvyfH9gMEikMVkwljx0xQZGmO94',
    appId: '1:672524255992:ios:bdeb91260e979d6bd2b10d',
    messagingSenderId: '672524255992',
    projectId: 'weather-app-50e4d',
    storageBucket: 'weather-app-50e4d.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3iAVaS_wHz7jIO5IQFg_cLfgBuMOFjy8',
    appId: '1:672524255992:web:c8b294f6403a8bcfd2b10d',
    messagingSenderId: '672524255992',
    projectId: 'weather-app-50e4d',
    authDomain: 'weather-app-50e4d.firebaseapp.com',
    storageBucket: 'weather-app-50e4d.firebasestorage.app',
    measurementId: 'G-JKDZWLGLNZ',
  );
}
